add mergeObjects() function
doctrine/mongodb-odm pull request #1897
Opened 2018-11-16 14:07 UTC by Romaxx

|      Q       |   A
|------------- | -----------
| Type         | feature
| BC Break     | no

#### Summary

2018-11-16 14:53 UTC, alcaeus requested changes
Thank you for your contribution. Apart from the comments below, please note the following:
- Please add tests as they are there for other aggregation pipeline operators. Take a look at `AggregationOperatorsProviderTrait` for guidance.
- Just adding the operator to `Expr` doesn't help, you also need to expose it in the `Operator` class.

We'll have to see how to deal with the two different syntaxes for `$mergeObjects`: it can take a single argument (e.g. when used as accumulator in a `$group` stage) or 2 or more arguments (when used in other stages or operators). This also affects some other operators (e.g. `$min` and `$max` and currently isn't properly handled).

Please also note that I'm scheduling this for 2.1 as we've got a whole load of aggregation operators that need adding. You can always create the operator manually through the `expression` helper in the meantime.

2018-11-16 14:53 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +     * @param Object1,Object2,...
This typehint is wrong, please refer to other methods for guidance.

2018-11-16 14:53 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +    public function mergeObjects()
Please look at other methods as to how to handle these arguments. Looking at the documentation for this operator, you can use `$expression1, $expression2, ...$expressions` and appropriate `@param` blocks. The `add` helper has a similar signature.

2018-11-16 14:53 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +        $arrayarg = array();
There's no need to copy the contents of `func_get_args` in a separate array, just pass them to the `operator` helper directly (again, see the `add` helper for example).

2018-11-16 14:53 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +
There are trailing spaces in this line which must not be there.

2023-11-04 13:33 UTC, malarzm commented
`mergeObjects` was introduced with https://github.com/doctrine/mongodb-odm/pull/2514

2023-11-04 13:33 UTC, closed without merging