Mark classes as @final and deprecate extending them
doctrine/mongodb-odm pull request #2008
Opened 2019-04-12 21:55 UTC by malarzm

Precedes #1984

2019-04-13 14:22 UTC, greg0ire approved these changes

2019-04-15 04:46 UTC, alcaeus requested changes
Missed a couple of package names in the deprecation messages 😅

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/DocumentNotFoundException.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/DocumentNotFoundEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/LoadClassMetadataEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/OnClassMetadataNotFoundEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/OnClearEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/OnFlushEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/PostCollectionLoadEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/PostFlushEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/PreFlushEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/PreLoadEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/PreUpdateEventArgs.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Hydrator/HydratorException.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Id/AlnumGenerator.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Id/AutoGenerator.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Id/IncrementGenerator.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Id/UuidGenerator.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/LockException.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/PersistentCollection.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionException.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Persisters/CollectionPersister.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Persisters/PersistenceBuilder.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Query/CriteriaMerger.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Query/FilterCollection.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Query/Query.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Query/QueryExpressionVisitor.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Query/ReferencePrimer.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/SchemaManager.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/UnitOfWork.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Utility/CollectionHelper.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 04:46 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Utility/LifecycleEventManager.php
> +            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in 2.0.', static::class, self::class), E_USER_DEPRECATED);
```suggestion
            @trigger_error(sprintf('The class "%s" extends "%s" which will be final in MongoDB ODM 2.0.', static::class, self::class), E_USER_DEPRECATED);
```

2019-04-15 06:48 UTC, malarzm commented
@alcaeus I think it'd be the first place where we add "MongoDB ODM" to the deprecation message, why now?

2019-04-15 06:50 UTC, malarzm commented
Ah nvm, just found #2010. Maybe I should go newest -> oldest when reading notifications :D

2019-04-15 07:02 UTC, alcaeus commented
Yeah, that was added afterwards when I gave it some more thought. I’ll fix those messages today or tomorrow, just thought that we should start somewhere 👍

2019-04-15 07:31 UTC, alcaeus approved these changes
Looks good, thanks @malarzm!

2019-04-15 07:31 UTC, merged