Provide rewindable option to Aggregation and Query builders/queries
doctrine/mongodb-odm pull request #2116
Opened 2019-11-20 22:22 UTC by Steveb-p

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes
| Fixed issues | #2113 

#### Summary

Proof of concept for allowing user control over wrapping resulting `Traversable`/`Iterator` with `CachingIterator` - to prevent memory issues when iterating over large result sets.

Note: This PR is incomplete - still needs tests and relevant comment blocks

2019-11-23 12:35 UTC, malarzm commented
So for the heads up, @alcaeus wants to evaluate one other approach/idea (but I'll let him do the explaining) and if it doesn't make sense, we'll go with this :)

2019-12-12 00:38 UTC, Steveb-p commented
@malarzm I've talked a little with @alcaeus over on slack about it, and he didn't seem sure about his approach. 

As far as I understood it, it revolved around creating a `WindowIterator` that would cache a specific amount of results instead of the whole result set.

However, either way I believe some way of allowing control over what iterators are added to iterator chain will be probably needed, whether it will be `rewindable` method for both `Builder`s or something else is up for discussion.

I've added commits with new `BaseIterator` class, since `PrimingIterator` requires `Iterator` instance as it's constructor argument and reducing it to `iterable` or `Traversable` might not do the trick - after all, there are plenty of instances where `Iterator` is specifically expected, not just any `Traversable`.  
Depending on `rewindable` option either `BaseIterator` or `CachingIterator` is used to wrap `Cursor`.

I've also slightly changed the way `CachingIterator` works. I've removed the `getIterator` private method as it was only used in `storeCurrentResult` method - which in turn was called in constructor once and on each `next` call. Now instead the wrapping `Generator` stores results directly in `$this->items` just before `yield`ing them (`storeCurrentResult` is still called in constructor).

```php
private function wrapTraversable(Traversable $traversable) : Generator
{
    foreach ($traversable as $key => $value) {
        $this->items[$key] = $value;
        yield $key => $value;
        $this->iteratorAdvanced = true;
    }

    $this->iterator = null;
}
```
 
I've removed `iteratorExhausted` property - now `Generator` removes it's reference immediately just before final return, which also signifies iterator exhaustion (`$this->iterator === null`). This also means that `Generator` is freed earlier - immediately after exhaustion - in case PHP messes up it's reference counts.

I've wondered if those two iterators - `BaseIterator` and `CachingIterator` - should have a common parent class, but almost every method differs and I'm not sure it is worth it creating such a class for them.

There are still some code quality checks / comment updates that I need to address, but I'd like to know your opinion if this approach is a valid one.

See new commits: https://github.com/doctrine/mongodb-odm/pull/2116/files/6e26070f7ad7a89f33bc5b1042133e0886118c4d..a312708b991c7c36d8bdaa1b581a70e007dff620

2019-12-17 07:26 UTC, alcaeus requested changes
Thanks for working on this logic! I've left some feedback in the code itself. Just a couple of points here:
* I'm not sure if the refactoring in `CachingIterator` is necessary. If it isn't, I'd prefer leaving it out as long as it doesn't have a performance impact.
* The code currently produces a lot of phpcs errors: https://travis-ci.org/doctrine/mongodb-odm/jobs/623925579#L2854. If you've installed dependencies locally, you can run `vendor/bin/phpcbf` to fix most of them. Then, run `vendor/bin/phpcs` to see what errors couldn't be fixed and fix them manually.
* PHPStan also complains about your code: https://travis-ci.org/doctrine/mongodb-odm/jobs/623925578#L1426. Reverting the refactoring in `CachingIterator` will fix some of them, while applying the `getIterator()` method to `BaseIterator` and updating the `$iterator` type hint as suggested below will fix the rest of them.
* This PR currently contains commits from another branch. I'll merge up through the branches soon, which should take care of that. We can worry about rebasing and squashing commits once the implementation is solid.

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +final class BaseIterator implements Iterator
`BaseIterator` makes it sounds like this is designed to be extended, which it isn't due to it being `final` and `@internal`. The SPL brings a `NoRewindIterator`, which would be a good name except that it behaves differently (it ignores calls to `rewind` instead of throwing an exception. What do you think of calling this `UnrewindableIterator`?

```suggestion
final class UnrewindableIterator implements Iterator
```

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +        if ($this->iteratorAdvanced) {
Suggest extracting this to a method to avoid duplicating logic here and in `rewind`:
```suggestion
        $this->preventRewinding(__METHOD__);
```

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +        $this->storeCurrentItem();
I feel like this call is superfluous: `wrapTraversable` stores the current key and value in `$this->key` and `$this->value` in the foreach loop, so I'm wondering why we still need this here.

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +        $wrapper = function () {
```suggestion
        $toArray = function () {
```

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +        return iterator_to_array($wrapper());
```suggestion
        return iterator_to_array($toArray());
```

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +            $this->key = $key;
Why do we store the key and value instead of accessing `$this->iterator->key()` and `$this->iterator->current()`?

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/CachingIterator.php
> -    private function getIterator() : Generator
This method is necessary to prevent PHPStan from throwing an error in our face: https://travis-ci.org/doctrine/mongodb-odm/jobs/623925578#L1441.

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/CachingIterator.php
> +            $this->items[$key] = $value;
I'd rather reuse `storeCurrentItem` here:
```suggestion
            $this->storeCurrentItem();
```

That said, I'm not sure why this refactoring is necessary, could you elaborate on that please?

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Query/Query.php
> +     * HydratingIterator, CachingIterator and BaseIterator expect a Traversable
Please use an [Oxford comma](https://en.wikipedia.org/wiki/Serial_comma) here:
```suggestion
     * HydratingIterator, CachingIterator, and BaseIterator expect a Traversable 
```

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
> +    public function rewindable(bool $rewindable = true) : self
Due to the work the aggregation builder is set up, this also requires a proxy method in `Doctrine\ODM\MongoDB\Aggregation\Stage`:
```php
public function rewindable(bool $rewindable = true) : self
{
    $this-builder->rewindable($rewindable);

    return $this;
}

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
> +     * @see https://github.com/doctrine/mongodb-odm/issues/2113
I believe we can omit this comment.

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +        /* If the iterator has advanced, exhaust it now so that future iteration
This comment is obsolete.

2019-12-17 07:26 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +    /** @var Generator */
```suggestion
    /** @var Generator|null */
```

This will fix the current PHPStan errors in this file, but most likely cause others. You can use the `getIterator()` method from `CachingIterator` to prevent these errors.

2019-12-31 09:45 UTC, Steveb-p commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +        $this->storeCurrentItem();
It's required to cause generator to reach first `yield`. Otherwise `Cursor` is not starting it's execution, which differs from what `CachingIterator` does. When creating this I worked under the assumption that this should not be changed.

Should I change the method name to something else, and if yes, what would you prefer?

2019-12-31 10:35 UTC, Steveb-p commented on lib/Doctrine/ODM/MongoDB/Query/Query.php
> +     * HydratingIterator, CachingIterator and BaseIterator expect a Traversable
Applied in 87fc9210df0a412b36be475e3e9f7b925aa8201a

2019-12-31 10:35 UTC, Steveb-p commented on lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
> +    public function rewindable(bool $rewindable = true) : self
Applied in 74ddf548fa0d781ebba8adcefaf40f79609016d6

2019-12-31 10:35 UTC, Steveb-p commented on lib/Doctrine/ODM/MongoDB/Iterator/CachingIterator.php
> +            $this->items[$key] = $value;
Reverted changes to `CachingIterator` in 3dd3423525672225acbebd4c4ebc72d5ff326edd

2019-12-31 10:37 UTC, Steveb-p commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +final class BaseIterator implements Iterator
Applied alongside other comments related to `UnrewindableIterator` (previously `BaseIterator`) in 907e08d5bee727860eac12ef51dc6392a654c613.

2019-12-31 10:38 UTC, Steveb-p commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +            $this->key = $key;
I do not know why I had it set up this way. It's probably a result of me using `CachingIterator` as base. Adjusted.

2019-12-31 10:38 UTC, Steveb-p commented on lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php
> +     * @see https://github.com/doctrine/mongodb-odm/issues/2113
Only the `@see` part, right? Adjusted :smile:

2020-01-01 22:46 UTC, Steveb-p commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +        $this->storeCurrentItem();
I've removed the method completely and only left `$this->iterator->key()` in `__construct` which - as far as I understand it, I may be wrong - starts up the generator causes `Cursor` to query and execute.

2020-01-08 09:25 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +        $this->storeCurrentItem();
Wouldn't the initial `foreach` already initialise the cursor and start iterating?

2020-01-08 12:16 UTC, Steveb-p commented on lib/Doctrine/ODM/MongoDB/Iterator/BaseIterator.php
> +        $this->storeCurrentItem();
```php
<?php

function wrapTraversable(Traversable $traversable) {
    echo("ITERATOR EXECUTING\n");
    foreach ($traversable as $key => $value) {
        yield $key => $value;
    }
};

$generator = wrapTraversable(new ArrayIterator([1, 2, 3]));

echo "BEFORE KEY\n";
$generator->key();
echo "AFTER KEY\n";

foreach ($generator as $key => $value) {
    echo $value;
}
```

Output:
```
/usr/bin/php /home/steveb/PhpstormProjects/adpanel/adpanel/test.php
BEFORE KEY
ITERATOR EXECUTING
AFTER KEY
123
```

Therefore, because `$this->iterator` is an instance of a `Generator`, it does not start executing (even until the first `yield` statement) until any call to the usual `Iterator` methods.

`CachingIterator` is - as far as I understand it - used to immediately start the `Cursor` and this call does exactly that, similarly to how `storeCurrentItem` was doing.

2020-02-04 11:48 UTC, alcaeus commented
Sorry for the long delay. Logic looks good now. Could you please add tests for the builder/query functionality to make sure no The [QueryTest](https://github.com/doctrine/mongodb-odm/blob/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/QueryTest.php) and BuilderTest classes (for [Aggregation](https://github.com/doctrine/mongodb-odm/blob/master/tests/Doctrine/ODM/MongoDB/Tests/Aggregation/BuilderTest.php) and [Query](https://github.com/doctrine/mongodb-odm/blob/master/tests/Doctrine/ODM/MongoDB/Tests/Query/BuilderTest.php)) serve as examples. After that, this is ready for a merge into 2.1 :)

2020-02-18 11:28 UTC, Steveb-p commented
@alcaeus I'll try to wrap this up tonight/tomorrow.

2020-02-18 11:31 UTC, alcaeus commented
No worries, caught up in things as well, so I can only finish it up next week anyway.

2020-02-19 23:32 UTC, Steveb-p commented
I've added tests in 9f347c6. If I misunderstood their purpose - being too generic or too narrow - please correct me.

They should not pass since I've deliberately marked them as expecting an exception to be thrown to show a little quirk/issue that those tests uncovered: empty resultsets will incorrectly **not** mark iterator as exhausted. This is due to the fact that foreach loop in wrapping `Generator` is never entered. I've tried setting `iteratorAdvanced` property to `true` after the `foreach` but since we expect the iterator to be started immediately this causes it to become unusable. I'm wondering if there is a graceful solution for this. WDYT?

2020-04-22 07:56 UTC, alcaeus commented
@Steveb-p once again, sorry for the long delay here, but I was not able to do any significant work over the past few weeks due to the current situation.

I updated the tests so they pass, and also added paragraphs to the query builder and aggregation builder documentation explaining this feature. Once I've got the other branches stable and merge up, this is good to merge.

Thanks for highlighting this issue, fixing it, and bringing along more patience a maintainer could ask for! ❤️

2020-04-22 07:56 UTC, alcaeus approved these changes

2020-04-22 10:10 UTC, merged