Refactor: introduce DocumentManagerInterface
doctrine/mongodb-odm pull request #2217
Opened 2020-08-16 21:35 UTC by babarinde

|      Q       |   A
|------------- | -----------
| Type         | bug/feature/improvement
| BC Break     | no

#### Summary

Add DocumentManagerInterface and use across library

2020-09-08 13:23 UTC, alcaeus requested changes
@babarinde I've finally had enough time to take a look at this. I've left comments on the look of the interface itself (as I don't believe all methods should be part of it) and left comments where switching from the `DocumentManager` implementation to the `DocumentManagerInterface` interface constitutes a BC break that needs to be avoided.

@malarzm any opinion on the look of the interface?

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/DocumentManager.php
> +    public static function create(?Client $client = null, ?Configuration $config = null, ?EventManager $eventManager = null) : DocumentManagerInterface
This return type should stay the same: for one, changing this is a BC break. More importantly, in this case we can say that `create` will always return an instance of itself, so there's no need for the interface here.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public function getProxyFactory() : ProxyFactory;
The proxy factory is a dependency of the document manager. Any other class that needs it should not fetch it from the manager, but rather receive it via dependency injection itself.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public static function create(?Client $client = null, ?Configuration $config = null, ?EventManager $eventManager = null) : DocumentManagerInterface;
I see no advantage in the interface requiring a factory: the advantage of different managers is that they can have different ways to be constructed. For example, a simple factory for a manager would be `create(string $connectionUri, array $options = []) : DocumentManagerInterface;`. Having this method as part of the interface forbids you from creating custom factories in implementations of the contract.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public function createQueryBuilder($documentName = null) : Query\Builder;
Making my life easier: all methods above this one should not be part of the interface IMO, as they mostly expose implementation details like dependencies or driver classes (which may not always be the same). Please start a discussion on any of the methods if you want to make a case for including them in the interface.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public function lock(object $document, int $lockMode, ?int $lockVersion = null) : void;
For the time being, I'd like to remove locking from the interface. I'm not convinced there are enough use-cases to warrant keeping it.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public function getConfiguration() : Configuration;
This method should not be part of the interface: any service relying on manager configuration should be created with a configuration instance itself.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public function createReference(object $document, array $referenceMapping);
This method should not be part of the interface, as it only contains internal functionality.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Event/LifecycleEventArgs.php
> +    public function getDocumentManager() : DocumentManagerInterface
This is a BC break since the `DocumentManagerInterface` doesn't contain all `DocumentManager` methods.

Please note that this applies to all event classes.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Id/IdGenerator.php
> +    public function generate(DocumentManagerInterface $dm, object $document);
This is a BC break: widening the parameter type in the interface is not allowed, as it makes existing implementations incompatible.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionInterface.php
> +    public function setDocumentManager(DocumentManagerInterface $dm);
This change is a BC break (see explanation above).

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Repository/DocumentRepository.php
> +    public function getDocumentManager() : DocumentManagerInterface
This is a BC break.

2020-09-08 13:23 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/AbstractCommand.php
> +     * @return DocumentManagerInterface
Strictly speaking, this is also a BC break. We may want to consider marking this class as `@internal` to avoid this.

2020-09-08 14:35 UTC, babarinde commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public function createQueryBuilder($documentName = null) : Query\Builder;
@alcaeus do you think getDocumentDatabase, getDocumentCollection and getDocumentBucket should not be part of the interface?

2020-09-08 14:36 UTC, babarinde commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public function lock(object $document, int $lockMode, ?int $lockVersion = null) : void;
i guess unlock should also be removed as well

2020-09-08 14:52 UTC, babarinde commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public function createQueryBuilder($documentName = null) : Query\Builder;
@alcaeus , While i agree that some of those methods be removed.
using the interface here https://github.com/doctrine/mongodb-odm/pull/2217/files#diff-ba2f525e9ff863e4a04dde560eaf81a6R69 will now affect https://github.com/doctrine/mongodb-odm/pull/2217/files#diff-ba2f525e9ff863e4a04dde560eaf81a6R72
We may have to revert  most constructors using the interface back to its original DM

2020-09-08 15:45 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/DocumentManagerInterface.php
> +    public function lock(object $document, int $lockMode, ?int $lockVersion = null) : void;
Yes, I forgot to mention that. Sorry.

2020-10-24 11:18 UTC, malarzm commented
First, I am sorry it took me this long to get to this PR. I think we won't get away from typehinting driver's classes in the interface without introducing an abstraction layer. We've been there with doctrine/mongodb and it wasn't that great. We need to accept the fact that we (and folks using ODM) depend directly on MongoDB's driver and library and live with it. Should there be any breaking change in said dependencies will require us to bump major version now and I think it's ok.

Also I think that for the interface to make sense we need to include all public methods of the DocumentManager as otherwise the implementations are not really interchangeable. If we come to an agreement that a method should not be part of an interface it most probably should be moved elsewhere (and eventually removed with 3.0).

Finally, more as a note to us maintainers, it'd be great to add some aliasing to the bundle so people can start depending on the interface in their codebases.

2021-01-12 19:35 UTC, alcaeus commented
After further discussion, we've decided to postpone this indefinitely as this will be a whole lot of BC breaks for a doubtful result. Thanks @babarinde for tackling this and we'll pick up where you left off if we decide to introduce an interface further down the line.

2021-01-12 19:35 UTC, closed without merging