Use symfony/deprecation-contracts to announce deprecations in code
doctrine/mongodb-odm pull request #2249
Opened 2020-11-26 10:30 UTC by alcaeus

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

#### Summary

This replaces manual calls to `@trigger_error` with `trigger_deprecation` from the `symfony/deprecation-contracts` package. This allows users to override the `trigger_deprecation` function to implement their custom logic.

Note that this PR drops deprecation functionality for field mapping annotations that were supposed to be dropped in 2.0. Since these methods are marked `@internal`, I have no problem dropping them in a minor release.

2020-11-26 17:32 UTC, SenseException requested changes

2020-11-26 17:32 UTC, SenseException commented on lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
> +                    '2.1',
"was deprecated in doctrine/mongodb-odm 2.2"
```suggestion
                    '2.2',
```

2020-11-26 17:32 UTC, SenseException commented on lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php
> +                '2.1',
"was deprecated in doctrine/mongodb-odm 2.2"
```suggestion
                '2.2',
```

2020-11-26 21:27 UTC, SenseException approved these changes

2020-11-27 08:44 UTC, merged

2020-12-05 23:41 UTC, malarzm reviewed
Definitely late to the party, but thanks for the change 👍