[2.2.x] Fix locking when ClassMetadata is unserialized
doctrine/mongodb-odm pull request #2281
Opened 2021-02-03 14:02 UTC by buffcode

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #2278

#### Summary

Caching / unserializing ClassMetadata broke locking functionality

2021-02-03 21:07 UTC, SenseException commented
@malarzm The website config lists 2.2.x as the maintained current branch and 2.3.x as the upcoming, while the default branch is set to 2.3.x. Which branch should this PR target?

2021-02-03 21:11 UTC, malarzm commented
This PR shall prevail :) I'll be closing the other ones and review this one shortly

2021-02-03 21:16 UTC, malarzm requested changes
Thanks for the PR! The change on it's own is great however we need to have it covered by a test to prevent regressions in future. At a glance this test here https://github.com/doctrine/mongodb-odm/blob/06a7f2fcd8dbf7c95218f217fbff8601ba26c92f/tests/Doctrine/ODM/MongoDB/Tests/Mapping/ClassMetadataTest.php#L36 looks like a good candidate.

2021-02-04 00:21 UTC, buffcode commented
@malarzm I have added assertions to the `ClassMetadataTest` for this issue. I've also added assertions for `isVersioned` and `versionField` though they are not affected, I hope thats okay.

2021-02-04 00:23 UTC, buffcode reviewed
Adressed in a97aab0c4703ad17eac1efaa9bbb66ad844990ae

2021-02-04 08:10 UTC, malarzm approved these changes
That's great, thanks for adding versioning to the test as well

2021-02-04 08:11 UTC, merged

2021-02-04 08:12 UTC, malarzm commented
Thanks @buffcode!