Add parameter type hints to tests
doctrine/mongodb-odm pull request #2369
Opened 2021-09-14 07:25 UTC by franmomu

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

I can split it in several PRs if it's necessary.

2021-09-14 21:21 UTC, SenseException commented on tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/MatchStageTest.php
> +    public function testProxiedExprMethods(string $method, $args = []): void
It doesn't look like there is a Closure in use. The previous `array` type seemed to be fitting. What do I miss?

2021-09-14 21:48 UTC, franmomu commented on tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/MatchStageTest.php
> +    public function testProxiedExprMethods(string $method, $args = []): void
Nothing 😬 , I do missed this because of the name of the function is used in other tests, thanks!

2021-09-15 21:56 UTC, SenseException approved these changes

2021-09-19 16:23 UTC, malarzm requested changes

2021-09-19 16:23 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
> +     * @return array<array{array|ArrayCollection|null}>
This looks like an overkill and I myself as a maintainer wouldn't like to write this, let alone contributors. Each array gets passed as arguments to a function that can be typed so I'd argue that's enough. Is there any way of opting out of defining types for data providers?

2021-09-21 21:39 UTC, franmomu commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
> +     * @return array<array{array|ArrayCollection|null}>
I was trying to add this information to also fix issues with phpcs sniff `SlevomatCodingStandard.TypeHints.ReturnTypeHint.MissingTraversableTypeHintSpecification` and fix issues with static analysis tools (phpstan level 6) where you should define the iterable type.

But I understand this may seem overkill, we could do the same here as the return types I guess, keeping the rule and for phpstan we could use something like https://github.com/phpstan/phpstan-phpunit/issues/63#issuecomment-592515871.

2021-10-23 13:30 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
> +     * @return array<array{array|ArrayCollection|null}>
That'd be great 🙏

2021-10-23 13:40 UTC, franmomu commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
> +     * @return array<array{array|ArrayCollection|null}>
I think I already removed those phpdoc (I may have left some, I'll check tomorrow)

2021-10-23 13:54 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/AtomicSetTest.php
> +     * @return array<array{array|ArrayCollection|null}>
Awesome, feel free to merge 👍

2021-10-23 13:55 UTC, malarzm approved these changes

2021-10-24 02:57 UTC, IonBazan approved these changes

2021-10-24 02:58 UTC, merged