add missing type declarations
doctrine/mongodb-odm pull request #2383
Opened 2021-10-28 08:33 UTC by franmomu

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

We can individually set up some checks to force type declarations (extracted from https://github.com/phpstan/phpstan-src/blob/master/conf/config.level6.neon)

2021-10-28 09:03 UTC, IonBazan approved these changes
Nice 👍🏻 Are we targeting to get level 6 in v2.3.0? If so, can you create an issue with checkboxes representing each rule to track the progress on that?

2021-10-29 21:16 UTC, SenseException requested changes

2021-10-29 21:16 UTC, SenseException commented on lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Out.php
> +            // @phpstan-ignore-next-line if $from is not a class-string is handled by the try-catch
The PHPStan issues should be put into the config file. Same with the other files.

2021-11-01 19:56 UTC, SenseException approved these changes

2021-11-19 07:55 UTC, franmomu commented
merged in https://github.com/doctrine/mongodb-odm/pull/2385

2021-11-19 07:55 UTC, closed without merging