Schema:create fails with single collection inheritance
doctrine/mongodb-odm pull request #2392
Opened 2021-11-23 10:00 UTC by JJarrie

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes
| Fixed issues | #2182 

#### Summary

Maintain in memory already processed collection in case of single collection inheritance and skip next procession of these collections.

2021-11-23 23:53 UTC, malarzm requested changes
Thanks @JJarrie for the PR! :tada: The solution you've provided is simple, we're requiring PRs to have tests not only to prove the solution is working, but to prevent regressions in the future. Could you please write one? Don't hesitate to ask should you need any help :)

2021-11-30 21:16 UTC, JJarrie commented
> Thanks @JJarrie for the PR! tada The solution you've provided is simple, we're requiring PRs to have tests not only to prove the solution is working, but to prevent regressions in the future. Could you please write one? Don't hesitate to ask should you need any help :)

Hello, I need some help. I tried to add the same structure as the one who raised the error in the issue ticket.

```php
<?php

declare(strict_types=1);

namespace Documents\Functional;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

/**
 * @ODM\MappedSuperclass
 * @ODM\InheritanceType("SINGLE_COLLECTION")
 * @ODM\DiscriminatorField("@type")
 * @ODM\DiscriminatorMap(SingleInheritanceCollectionSuperClass::TYPES)
 */
class SingleInheritanceCollectionSuperClass
{
    public const TYPES = [
        'subType1' => SingleInheritanceCollectionSubType1::class,
        'subType2' => SingleInheritanceCollectionSubType2::class,
    ];

    /** @ODM\Id */
    private $id;

    /** @ODM\Field(type="string") */
    private $name;
}
```

```php
<?php

declare(strict_types=1);

namespace Documents\Functional;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

/**
 * @ODM\Document
 */
class SingleInheritanceCollectionSubType1 extends SingleInheritanceCollectionSuperClass
{
    /** @ODM\Field(type="string") */
    private $someFieldA;
}

```

```php<?php

declare(strict_types=1);

namespace Documents\Functional;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

/**
 * @ODM\Document
 */
class SingleInheritanceCollectionSubType2 extends SingleInheritanceCollectionSuperClass
{
    /** @ODM\Field(type="string") */
    private $someFieldB;
}
```

And as the database is mocked in SchemaManagerTest::testCreateCollections, the original error (coming from database) is not raised. And I have some difficulties to understand how to handle my case into the functionnal suite. If someone have an idea or an explanation, I take it.

:)

2021-12-02 03:42 UTC, IonBazan commented
@JJarrie I've added a test which makes sure one of our existing documents using single collection inheritance trigger the collection creation only once.

2021-12-06 20:21 UTC, JJarrie commented
> @JJarrie I've added a test which makes sure one of our existing documents using single collection inheritance trigger the collection creation only once.

@IonBazan thank you for your help.

2021-12-06 22:14 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php
> +        self::assertSame(1, array_count_values($createdCollections)['Tournament']);
To prevent this test from becoming obsolete there should be an assertion in the beginning that Tournament has inheritance and is using single collection. Otherwise the change in existing entities can render this test useless

2021-12-27 23:07 UTC, malarzm approved these changes

2021-12-27 23:07 UTC, merged

2021-12-27 23:08 UTC, malarzm commented
Thanks @JJarrie!