Initialize proxy when document is not initialized
doctrine/mongodb-odm pull request #2399
Opened 2021-12-26 12:03 UTC by franmomu

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | yes
| Fixed issues | #2349

#### Summary

Taking a look at #2349 seems like the problem is that the proxy is not initialized when it's managed. 

Looking at the code, if the document is an instance of `GhostObjectInterface` and it not initialized, it calls to `$document->setProxyInitializer(null);` which removes the initialization.

To be honest I'm not sure if it's the right fix, maybe that code was there for some reason.

2021-12-26 17:06 UTC, malarzm requested changes

2021-12-26 17:06 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/UnitOfWork.php
> +                $document->initializeProxy();
This seems to do the trick, but we shouldn't initialize the object at this point as this will lead to a db query while we already have data waiting for hydration. The correct fix would be to somehow initialize properties not managed by the ODM

2021-12-26 19:12 UTC, franmomu commented on lib/Doctrine/ODM/MongoDB/UnitOfWork.php
> +                $document->initializeProxy();
Thanks @malarzm! that makes sense, I'll try to take a look how the ORM does this if I can. In the meantime I leave the test here just in case someone wants to give it a try

2022-03-03 11:02 UTC, franmomu commented
I was taking a look again at this issue and one possible solution would be to skip these properties.

I've skipped the typed non-mapped properties that have a default value. What about this? maybe is there something else to take into account? 🤔

2023-03-17 13:12 UTC, carlos-granados commented
@malarzm any chance that this might be merged? We are experiencing this issue with Doctrine 2.3 and were hoping to see it solved when we upgrade to 2.4

2023-03-17 17:39 UTC, alcaeus commented
2.4 is already released. I'll take a look at this after the weekend for inclusion in a 2.5 patch release.

2023-03-22 12:08 UTC, alcaeus commented
I made some adjustments to the tests to no longer rely on the absence of an error (and instead running an assertion), as well as applying the logic to all unmapped properties, not only those with default values.

2023-03-22 18:18 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2349Test.php
> +            self::assertSame([], $customer->getEvents()); // This would trigger an error if unmapped properties are unset
This test seems fragile:

- we don't check whether `$customer` is indeed a proxy
- and is it still uninitialized (the test would still pass)

Maybe a db query count would be also good to assert so we never get into situation like the one found in original PR?

2023-03-22 18:18 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
> +        $skippedNonMappedFieldsFqns = $this->getUnmappedPropertyFqns($metadata);
This looks more expensive than the original identifier exclusion and is called each and every time we create a proxy object, pretty much a hot path. We should memoize the result of `skippedFieldsFqns` per `$metadata`

2023-03-22 18:18 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
> +            if ($metadata->hasField($propertyName)) {
Just a note as field with different PHP and DB field always confused me: metadata is operating on PHP's object properties, and DB field name is used only in hydrators/persisters, right? If yes then we're A-OK here

2023-03-22 18:18 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2349Test.php
> +/** @requires PHP 7.4 */
If I'm seeing correctly, 7.4 was already minimal version for ODM 2.5.x :) No harm done given we haven't cleaned this up yet, worth doing before 2.6.x :)

2023-03-22 18:20 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2349Test.php
> +            self::assertSame([], $customer->getEvents()); // This would trigger an error if unmapped properties are unset
Also i believe this would be better placed in a generic proxy test, where we don't even need database operations. Just creating a proxy and asserting whether unmapped stuff can be used without initialization - this should be easier to maintain in future

2023-03-23 10:44 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Proxy/Factory/StaticProxyFactory.php
> +        $skippedNonMappedFieldsFqns = $this->getUnmappedPropertyFqns($metadata);
Or put into metadata itself?

2024-11-18 12:10 UTC, alcaeus commented
Fixed by #2698 - I had forgotten about this PR until after merging the other PR. Thanks for your efforts @franmomu!

2024-11-18 12:10 UTC, closed without merging