add BackedEnum support
doctrine/mongodb-odm pull request #2412
Opened 2022-02-20 07:14 UTC by IonBazan

|      Q       |   A
|------------- | -----------
| Type         | feature
| BC Break     | no
| Fixed issues | #2404 

#### Summary

Provides native support for `BackedEnum`s. This could be later integrated with #2411 to allow even better DX.

2022-02-21 07:57 UTC, IonBazan commented
This is now ready for review. Please note that the "required" Coding Standards run will not be executed because I changed the PHP version there so the required name no longer match repository settings.

2022-02-21 20:21 UTC, malarzm requested changes
Great you took care of porting adding the feature! Beside my remarks above please also add a relevant documentation.

Food for thought: in the past it was requested that we pass `$mapping` to types. While I'm still reluctant to do so it'd make the implementation easier as we'd just add new `enum` type that would read target enum from the mapping. Thoughts on this?

2022-02-21 20:21 UTC, malarzm commented on .github/workflows/coding-standards.yml
> +    uses: "doctrine/.github/.github/workflows/coding-standards.yml@1.4.1"
I think the part changing CS could go into 2.3 as a separate PR so we can have one list of jobs required to pass for a PR. Thoughts?

2022-02-21 20:21 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/Annotations/Field.php
> +        ?string $type = 'string',
We need to remember to change the default value here as #2411 did

2022-02-21 20:21 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/Driver/XmlDriver.php
> +                if (isset($mapping['enum-type'])) {
This looks fishy given the check above and below are checking (and assigning from) the `$attributes` array.

2022-02-21 20:21 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
> +            'Attempting to map non-enum type %s as enum in document class %s::$%s',
```suggestion
            'Attempting to map a non-enum type %s as an enum: %s::%s',
```

This should be the most consistent with other exceptions we have

2022-02-21 20:21 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
> +        return new self(sprintf('Enum types require PHP 8.1 in %s::$%s', $className, $fieldName));
```suggestion
        return new self(sprintf('Enum types require PHP 8.1 in %s::%s', $className, $fieldName));
```

We don't use `$` in other exceptions

2022-02-21 20:21 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
> +            'Trying to hydrate enum property "%s::$%s". Problem: Case "%s" is not listed in enum "%s"',
```suggestion
            'Trying to hydrate an enum property %s::%s, but "%s" is not listed as one of "%s" cases',
```

2022-02-21 20:21 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/MappingException.php
> +    public static function invalidEnumValue(
This one is definitely not a mapping exception but rather a https://github.com/doctrine/mongodb-odm/blob/2.3.x/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorException.php

2022-02-21 20:21 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/ReflectionEnumProperty.php
> +class ReflectionEnumProperty extends ReflectionProperty
It's a pity this class did not went into a common repository. If you're not willing to pursue this then it should be final and marked as `@internal`

2022-02-21 20:21 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/ReflectionEnumProperty.php
> +        return $enum->value;
Given this class is usable and actually loaded only in PHP 8.1 we should be safe to call
```suggestion
        return $this->originalReflectionProperty->getValue($object)?->value;
```
but feel free to ignore, probably there's a lot more places that would benefit from the approach in the future and by then we'll have a CS-rule that'd autofix everything.

2022-02-21 20:21 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Documents81.Card.dcm.xml
> +        <field name="nullableSuit" type="string" enum-type="Documents81\Suit" nullable="true" />
When we go down type-inferring rule we'll need to think how to correctly choose string vs int for the type conversion.

2022-02-21 20:23 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/ReflectionEnumProperty.php
> +class ReflectionEnumProperty extends ReflectionProperty
@beberlei do you have any insights why ReflectionEnumProperty isn't a part of https://github.com/doctrine/persistence/tree/2.3.x/lib/Doctrine/Persistence/Reflection?

2022-02-22 05:30 UTC, IonBazan commented on tests/Doctrine/ODM/MongoDB/Tests/Mapping/xml/Documents81.Card.dcm.xml
> +        <field name="nullableSuit" type="string" enum-type="Documents81\Suit" nullable="true" />
We can check if the enum class implements `StringBackedEnum` or `IntBackedEnum` to detect the underlying type.

2022-02-22 05:50 UTC, IonBazan commented on lib/Doctrine/ODM/MongoDB/Mapping/ReflectionEnumProperty.php
> +        return $enum->value;
This `$enum` seems to become `null` when it's `null` in DB so I reverted that. See: https://github.com/doctrine/mongodb-odm/runs/5283674934?check_suite_focus=true

2022-02-22 08:07 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/ReflectionEnumProperty.php
> +        return $enum->value;
That's because the `?` in `?->` got lost :)

2022-02-22 10:05 UTC, IonBazan commented on lib/Doctrine/ODM/MongoDB/Mapping/ReflectionEnumProperty.php
> +        return $enum->value;
You are right @malarzm but after second thought, I decided to keep it pre-PHP8.1 compatible. This is in case someone accidentally imports this class in their code which would trow a really bad syntax error. I think we could revisit that topic once we decide to drop older PHP versions.

2022-03-06 17:48 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/ReflectionEnumProperty.php
> +class ReflectionEnumProperty extends ReflectionProperty
While waiting for doctrine/common merge and release we could add this class (final and internal). Once doctrine/common is there we'll change implementation :)

2022-03-08 16:15 UTC, malarzm commented
#2411 was merged, this needs to be rebased (it's conflicting anyway) and adapted :)

2022-03-08 17:00 UTC, IonBazan commented on lib/Doctrine/ODM/MongoDB/Mapping/ReflectionEnumProperty.php
> +class ReflectionEnumProperty extends ReflectionProperty
@malarzm What about the exception thrown? The `doctrine/persistence` one throws native `ValueError`, while here we are converting it to a `HydratorException` which is not available in `doctrine/persistence`. I suggest simplifying this implementation to throw native error instead too for easier migration.

2022-03-08 17:03 UTC, IonBazan commented
@malarzm rebased and adjusted accordingly. I will keep it as separate commits for cleaner diffs but I'll squash them once approved.

2022-03-08 17:09 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/ReflectionEnumProperty.php
> +class ReflectionEnumProperty extends ReflectionProperty
The HydratorInterface doesn't make any promises on what exceptions can be thrown, but generally it throws HydratorException when something is off with data (https://github.com/doctrine/mongodb-odm/blob/2.3.x/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php#L333). If possible and relatively simple I'd wrap native ValueError with our HydratorException. If it's not simple then let's the native error be thrown, we can't save users from everything :)

2022-03-08 17:30 UTC, franmomu commented on lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
> + *      enumType?: class-string<BackedEnum>|null,
```suggestion
 *      enumType?: class-string<BackedEnum>,
```
I guess `enumType` cannot contain `null`

2022-03-08 17:30 UTC, franmomu commented on lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
> + *      enumType?: class-string<BackedEnum>|null,
```suggestion
 *      enumType?: class-string<BackedEnum>,
```

2022-03-22 11:13 UTC, IonBazan commented
Since `doctrine/persistence` v2.4 is release, we can now use it. I decided to drop the custom `ReflectionProperty` and keep throwing the `ValueError` if something goes wrong (to be consistent with normal fields).

2022-03-27 11:07 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
> +        if (PHP_VERSION_ID >= 80100 && ! $type->isBuiltin() && enum_exists($type->getName(), true)) {
Please add this feature to documentation https://github.com/doctrine/mongodb-odm/pull/2411/files#diff-239d9a128ce24a76e204d8b9821ce009ef5c7b16298d549165da9bc05d5d8f97 created

2022-03-27 11:07 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php
> +            assert($type instanceof ReflectionNamedType);
`null` case is not handled (assert is just for PHPStan). Using a non-backed enum should warrant an exception

2022-04-29 18:14 UTC, VincentLanglet commented
What's need to finish this PR ? Do you need help ?
Seems to be a blocking point for the 2.4 version with doctrine/persistence v3 support (cf https://github.com/doctrine/mongodb-odm/pull/2428#issuecomment-1111467384)

2022-04-29 18:36 UTC, malarzm commented
FWIW I'll be wrapping this up over the weekend.

2022-04-30 15:21 UTC, IonBazan commented
Thanks @malarzm for taking over. Sorry, I didn't have enough time to make it prod-ready.

2022-05-03 12:10 UTC, malarzm commented
Merged in #2440

2022-05-03 12:10 UTC, closed without merging