Add PHPStan check for iterable types
doctrine/mongodb-odm pull request #2437
Opened 2022-04-30 11:26 UTC by franmomu

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

Last PR to add the PHPStan check for iterable types, the remaining ones where the ones in `tests`.

2022-05-04 23:13 UTC, malarzm requested changes
I'm not saying "definitely no", but given few definitions are off and tests are green I'm not sure these changes provide any real value other than satisfying SA tools. Maybe we could stay with level 5 for tests and improve just the main codebase for higher levels? To add another pro some time ago while working on sanity checks I needed to ignore phpstan/psalm errors in tests because I wanted to pass wrong values to check if exceptions are raised properly.

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Aggregation/AggregationOperatorsProviderTrait.php
> +     * @return mixed[]
```suggestion
     * @return Closure|mixed[]
```

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/ProjectTest.php
> +     * @param mixed[] $args
FWIW I'm not really a fan of adding `mixed[]` all over the place, IMO this is bringing little to no value

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Events/LifecycleListenersTest.php
> +     * @param mixed[] $args
Can we somehow note that first element should be an instance of `LifecycleEventArgs` (and we don't care about the rest)?

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/CommitImprovementTest.php
> +     * @param mixed[] $args
Same question as before with `LifecycleEventArgs`

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/ReadPreferenceTest.php
> +     * @param array<array<string, string>> $tags
Shall we introduce a `ReadPreferenceTagsShape` shape similar to `SortShape`?

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1232Test.php
> +     * @return array<string, mixed>|int|object|null
Isn't this returning `GH1232Comment[]`?

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2002Test.php
> +     * @psalm-param array{"$ref": string, class: class-string} $expectedReference
The `class` key is available only in first dataset. This makes me believe these changes are not really helpful :)

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH560Test.php
> +     * @param mixed[] $args
Here goes `LifecycleEventArgs` question again

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM83Test.php
> +     * @param mixed[] $args
I'm just marking all places with `LifecycleEventArgs` I see in case there'd be a place to improve (next 2 classes could use this as well)

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/MODM95Test.php
> +     * @param array<MODM95TestEmbeddedDocument>|Traversable<MODM95TestEmbeddedDocument> $embeddedDocuments
Both `@param` and code could be improved to use `iterable<MODM95TestEmbeddedDocument>` which wasn't available at the time of writing the test

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Persisters/PersistenceBuilderTest.php
> +     * @param array<string, mixed>|null $preparedData
I doubt that `null` should be allowed for `$preparedData` as the very first thing we do is iterate over it :)

2022-05-04 23:13 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/UnitOfWorkTest.php
> +     * @param array<string, string>|null $updateData
There are currently also ints and bools in the array

2022-11-03 23:48 UTC, franmomu commented
> I'm not saying "definitely no", but given few definitions are off and tests are green I'm not sure these changes provide any real value other than satisfying SA tools. Maybe we could stay with level 5 for tests and improve just the main codebase for higher levels? To add another pro some time ago while working on sanity checks I needed to ignore phpstan/psalm errors in tests because I wanted to pass wrong values to check if exceptions are raised properly.

Thanks @malarzm for the review! I've finally found some time to take a look at this again. I've just updated the code with the comments and make it green improving a bit some of the `mixed[]` types.

I'll try now to add another commit removing some of the phpdoc that don't add value and adding them to the baseline.

2022-11-04 22:43 UTC, malarzm commented
Awesome! Let me know if you'd need anything :)

2022-11-05 13:08 UTC, franmomu commented
I think it's ready to review, I understand the `mixed[]` vs `array` concern, to me when I see `mixed[]` it's like the type has been reviewed, but maybe `list<mixed>` would be better to express that it is list of mixed types and the key doesn't matter.

2022-11-06 20:40 UTC, malarzm approved these changes
Thank you very much @franmomu for your hard work on this 🍻

2022-11-06 20:40 UTC, malarzm commented on tests/Doctrine/ODM/MongoDB/Tests/Events/LifecycleListenersTest.php
> +     * @param array{LifecycleEventArgs} $args
Cool this was possible :)

2022-11-06 20:42 UTC, merged