Add some generic information
doctrine/mongodb-odm pull request #2439
Opened 2022-05-01 08:59 UTC by franmomu

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

To reach level 6 of PHPStan the remaining check is about generics, there are ~110 errors. This PR fixes some the "easy" ones.

The rest I guess that will involve making some classes generic (`Query` and `Aggregate` probably) and that would mean more errors and changes.

2022-05-03 10:37 UTC, IonBazan approved these changes
I just wish PHPStan would allow default values for template values.

2022-05-04 22:31 UTC, malarzm requested changes

2022-05-04 22:31 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/PersistentCollection/AbstractPersistentCollectionFactory.php
> +     * @psalm-return BaseCollection<array-key, TDocument>
This looks wrong: `TDocument` is taken from the parameter (which tells what class should be instantiated) and is definitely not what is later stored in the collection (we don't know what it'll be at this point). The only thing we can be kind-of-certain is that `$collectionClass` is a descendant of the `Collection` interface.

2022-05-08 21:57 UTC, franmomu commented on lib/Doctrine/ODM/MongoDB/PersistentCollection/AbstractPersistentCollectionFactory.php
> +     * @psalm-return BaseCollection<array-key, TDocument>
yeah, totally right, I missed this, thanks!

2022-05-08 22:39 UTC, malarzm approved these changes

2022-05-09 18:01 UTC, SenseException approved these changes

2022-05-09 18:02 UTC, merged