Add pipeline to $lookup stage
doctrine/mongodb-odm pull request #2459
Opened 2022-09-03 08:50 UTC by khaperets

|      Q       |   A
|------------- | -----------
| Type         | feature
| BC Break     | yes
| Fixed issues | #1863 

#### Summary

Added a pipeline lookup functionality that helps a lot in the futures developments,

2022-09-16 09:40 UTC, Ravetracer commented
I discovered that "foreignField" and "localField" is not mandatory when using "pipeline" in the $lookup stage. In fact it dropped the performance in our case so we had a query running for about 4 seconds. Without foreignField and localField the query runs in 250-300ms and the result set was the same.
Also it would be great if you can add an option to set variables using "let".

2022-09-16 10:16 UTC, khaperets commented
@Ravetracer Thanks for your comment. Changes pushed to PR.

2022-09-18 13:17 UTC, malarzm commented
@khaperets thanks for the PR! It seems that the test you've added is failing: https://github.com/doctrine/mongodb-odm/actions/runs/3067090011/jobs/4971970883#step:12:1783. The rest of errors seems to be unrelated, we'll investigate them. Once the test is green please fix coding standards, this can be done by running `vendor/bin/phpcbf` command. If possible, please also squash your commits so there's just one.

2022-09-18 18:05 UTC, khaperets commented
@malarzm I've done everything, thank you for the feedback.

2022-09-20 22:15 UTC, malarzm commented
@khaperets we've managed to get checks back to shape. May I ask you to rebase your PR atop newly created `2.5.x` branch?

2022-09-20 22:27 UTC, khaperets commented
@malarzm done

2022-09-20 22:50 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
> +        } else {
According to https://www.mongodb.com/docs/manual/reference/operator/aggregation/lookup/#correlated-subqueries-using-concise-syntax MongoDB 5.0 allows using all 4 fields together so the current these-or-those doesn't seem like a good idea.

2022-09-20 23:16 UTC, khaperets commented on lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
> +        } else {
fixed

2022-09-23 20:24 UTC, khaperets commented
@malarzm Added compatibility with MongoDB 5.0

2022-09-26 17:42 UTC, malarzm requested changes

2022-09-26 17:42 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
> +        $isSupportsPipelineWithLocalField = version_compare($serverVersion, '5.0') >= 0;
Generally we're letting end users handle version-specific behaviour as they do know what MongoDB version they're running. The most important reason is to prevent additional communication with database, as introduced here. So instead I'd rather see a way to reset builder's `localField` and `foreignField` properties when adding `pipeline`/`let`. I think the cleanest way to do will be a new method `resetLocalAndForeignField` that will `unset` both properties. Additionally this will allow use cases like https://github.com/doctrine/mongodb-odm/pull/2459#issuecomment-1249154690 to control how they query will be ran.

Also I didn't manage to comment last time, but I believe I've seen the test fail due to MongoDB version. Once we get back to letting users control the behaviour, you can skip some tests using methods like `\Doctrine\ODM\MongoDB\Tests\BaseTest::requireMongoDB42`.

Also feel free to ask me anything on our Slack, that way I'll be able to help faster :)

2022-10-02 09:49 UTC, malarzm approved these changes

2022-10-02 10:05 UTC, malarzm commented
Merged manually in https://github.com/doctrine/mongodb-odm/commit/7ebc038973587222c89de11cad4367c2185776f9. Thanks a lot @khaperets!

2022-10-02 10:05 UTC, closed without merging