use aggregation builder in lookup stage pipeline
doctrine/mongodb-odm pull request #2486
Opened 2022-12-07 12:37 UTC by aturki

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 2474

#### Summary

This PR provides implementation for using the aggregation builder as an argument to pipeline in the $lookup stage

2023-01-18 13:41 UTC, alcaeus requested changes

2023-01-18 13:41 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
> +     * @param Builder|Stage $pipeline
I suggest using `Builder|Stage|array<array<string, mixed>>` as argument: there's no reason why people shouldn't be allowed to pass an assembled pipeline to this method.

2023-01-18 13:41 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
> +        }
In case `$this->pipeline` ends up being a builder, we should ensure that it's not identical to `$this->builder` as that would result in some really nasty pipelines as well as potentially infinite recursion.

2023-02-11 19:53 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
> +        if ($this->pipeline instanceof Builder && $this->builder === $this->pipeline) {
Since the === operator is optimised we don't need to check the pipeline type first. Checking whether it's identical to the builder should be sufficient.

2023-02-12 08:24 UTC, franmomu commented on lib/Doctrine/ODM/MongoDB/Aggregation/Stage/Lookup.php
> +        if ($this->pipeline instanceof Builder && $this->builder === $this->pipeline) {
Thanks! I started doing this check at the beginning of the method and then didn't update it

2023-02-14 07:21 UTC, alcaeus approved these changes
A couple of notes on indentation and not applying filters in pipeline calls, but LGTM besides those.

2023-02-14 07:21 UTC, alcaeus commented on tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/LookupTest.php
> +            $this->assertEquals($expectedPipeline, $builder->getPipeline(false));
Indentation seems off here. Also, I'd expect this to work just the same with `true` being passed, as the parameter was introduced for nested pipelines only.

2023-02-14 07:21 UTC, alcaeus commented on tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/LookupTest.php
> +        $this->assertEquals($expectedPipeline, $builder->getPipeline(false));
This and following `getPipeline` calls should not set `$applyFilters` to false.

2023-02-15 07:01 UTC, franmomu commented on tests/Doctrine/ODM/MongoDB/Tests/Aggregation/Stage/LookupTest.php
> +            $this->assertEquals($expectedPipeline, $builder->getPipeline(false));
😕 fixed

2023-02-15 07:59 UTC, alcaeus commented
Thanks @aturki and @franmomu!

2023-02-15 07:59 UTC, merged