Custom _id for GridFS documents (#2487)
doctrine/mongodb-odm pull request #2489
Opened 2022-12-12 11:11 UTC by andrey-tech

|      Q       |   A
|------------- | -----------
| Type         |  feature
| BC Break     | no
| Fixed issues | #2487
| Version        | 2.5.x

#### Summary

Added two missing options to `UploadOptions`:
- `id` (mixed): File document identifier. Defaults to a new ObjectId.
~~- `disableMD5` (boolean): When true, no MD5 sum will be generated for the stored file. Defaults to `false`.~~

~~The `mongodb/mongodb` **^1.4.0** is required for option `disableMD5`.~~

2022-12-12 13:14 UTC, andrey-tech commented
It might make sense to change the property name from `_id` to `id` in `UploadOptions` for PHP CodeSniffer with Slevomat coding standard rules.

2022-12-13 06:02 UTC, andrey-tech commented
1) Renamed `_id` to `id` in `UploadOptions` for PHP CodeSniffer with SlevomatCodingStandard rules.
2) Added tests for new options `id` and `disableMD5`.

2022-12-13 07:26 UTC, franmomu commented
Hi @andrey-tech, thanks for the PR! since this is a feature, can you please target to `2.5.x` instead?

2022-12-13 07:50 UTC, andrey-tech commented
@franmomu Done.

2022-12-14 22:41 UTC, malarzm approved these changes
Thanks for the PR! Mind adding one more test please? :)

2022-12-14 22:41 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Repository/DefaultGridFSRepository.php
> +            $options['_id'] = $this->class->getDatabaseIdentifierValue($uploadOptions->id);
Would be great to have a test that covers type transformation

2022-12-21 07:13 UTC, andrey-tech commented on lib/Doctrine/ODM/MongoDB/Repository/DefaultGridFSRepository.php
> +            $options['_id'] = $this->class->getDatabaseIdentifierValue($uploadOptions->id);
MongoDB documentation lists `ObjectId` as just one of the common variants for the [_id field](https://docs.mongodb.com/manual/core/document/#the-_id-field).  So I removed type transformation from method `prepareOptions()` of class `DefaultGridFSRepository` for more flexibility. Test that covers this type transformation not needed anymore.

2023-01-18 13:28 UTC, alcaeus requested changes

2023-01-18 13:28 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Repository/UploadOptions.php
> +    public $disableMD5;
Do you have a specific use-case for the `disableMD5` option? The reason I omitted this was that the [specification](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst) marks the option as deprecated and it will be removed from the PHP driver in the next major release. I would prefer not adding it in now, as we'd have to do another BC break for 3.x then (as opposed to breaking it once for people migrating to ODM 2.0).

2023-01-18 13:28 UTC, alcaeus commented on composer.json
> +        "mongodb/mongodb": "^1.4.0",
Might as well bump this to 1.15 while you're at it. 1.4 is ancient and no longer supported, we should encourage people to upgrade :)

2023-01-21 21:48 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/Repository/UploadOptions.php
> +    public $disableMD5;
This one's on me (https://github.com/doctrine/mongodb-odm/issues/2487#issuecomment-1345624957) I didn't know it's deprecated :)

2023-01-22 11:42 UTC, andrey-tech commented on composer.json
> +        "mongodb/mongodb": "^1.4.0",
I don't mind :)

2023-01-23 07:19 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Repository/UploadOptions.php
> +    public $disableMD5;
Hehe, yes. We deprecated it since using MD5 is forbidden when being compliant with [FIPS](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards), and personally I wouldn't rely on MD5 for checksums anymore. @andrey-tech do you mind dropping it? I don't think we should introduce the option at this point, especially since we haven't had anyone ask for it.

2023-01-23 07:23 UTC, andrey-tech commented on lib/Doctrine/ODM/MongoDB/Repository/UploadOptions.php
> +    public $disableMD5;
@alcaeus I don't mind.

2023-01-23 07:25 UTC, andrey-tech commented on lib/Doctrine/ODM/MongoDB/Repository/UploadOptions.php
> +    public $disableMD5;
@malarzm Do you mind dropping it?

2023-01-23 08:45 UTC, andrey-tech commented on composer.json
> +        "mongodb/mongodb": "^1.4.0",
@malarzm Do you mind to set `^1.15.0`?

2023-02-15 11:59 UTC, franmomu commented on lib/Doctrine/ODM/MongoDB/Repository/UploadOptions.php
> +    public $disableMD5;
@andrey-tech since it's deprecated and it was not added on purpose, we should not add it

2023-02-18 14:57 UTC, andrey-tech commented on lib/Doctrine/ODM/MongoDB/Repository/UploadOptions.php
> +    public $disableMD5;
The deprecated option `disableMD5` has been removed from this PR.

2023-02-18 15:02 UTC, andrey-tech commented on composer.json
> +        "mongodb/mongodb": "^1.4.0",
I set `mongodb/mongodb` to `^1.15.0`.

2023-02-21 08:57 UTC, alcaeus approved these changes
LGTM.

We should add a test for using an identifier with a custom type, but I'm fine deferring that to a separate pull request.

2023-02-21 09:48 UTC, IonBazan commented
@alcaeus I think many people are still stuck on older versions and I wouldn't force them to update to v1.15 yet, especially that it requires updating the PHP extension via `pecl` which may not be an easy option, depending on their infrastructure.
There are still number of installs of older version. Would you consider relaxing the requirement to `^1.8.0` or `^1.10.0` instead?
<img width="907" alt="image" src="https://user-images.githubusercontent.com/1985514/220308454-386d6ff8-a7d1-4170-bf23-c4e2eec28a89.png">

2023-02-21 09:56 UTC, alcaeus commented
Bumping to `^1.10` seems sensible in that case. I'm aware that this will require folks to upgrade their extension, but considering that we don't support anything older than 1.15, they should've upgraded already :)

2023-02-21 10:01 UTC, alcaeus commented on .github/workflows/continuous-integration.yml
> +            driver-version: "1.10.0"
mongodb/mongodb `1.10` requires `ext-mongodb` `1.11` - we've corrected this with 1.15 to restore version number parity.

2023-02-21 10:14 UTC, IonBazan commented on .github/workflows/continuous-integration.yml
> +            driver-version: "1.10.0"
Noted, thanks! Some builds are canceled because of `ubuntu-18.04` being deprecated but 20.04 doesn't play well with the `mongodb-labs/drivers-evergreen-tools` action. Let's look into that in a separate PR.

2023-02-21 13:13 UTC, alcaeus commented on .github/workflows/continuous-integration.yml
> +            driver-version: "1.10.0"
I'll take a look 👍

2023-02-24 09:22 UTC, merged

2023-02-24 09:22 UTC, alcaeus commented
Thanks @andrey-tech!