Make `doctrine/annotations` dependency optional
doctrine/mongodb-odm pull request #2498
Opened 2022-12-27 12:11 UTC by franmomu

|      Q       |   A
|------------- | -----------
| Type         | task
| BC Break     | no
| Fixed issues | 

#### Summary

Similar to https://github.com/doctrine/orm/pull/8787, we have PHP attributes and XML mapping, there is no need to be a hard dependency.

2022-12-27 13:54 UTC, malarzm reviewed
This warrants an UPDATE file entry IMO. On the other hand I'm thinking if it's worth doing in a minor version.

2022-12-27 13:54 UTC, malarzm commented on composer.json
>      },
`doctrine/annotations` could be added to the `suggest` section

2022-12-27 13:54 UTC, malarzm commented on composer.json
> +        "doctrine/annotations": "<1.12 || >= 3.0"
nitpicking, but one operator has an extra space while the other one does not ;)

2022-12-27 18:16 UTC, SenseException commented on composer.json
>      },
Having them in the suggestions can help if people read them and still need annotations. Older PHP versions still need them.

2022-12-27 18:17 UTC, SenseException approved these changes
After adding annotations to composer-suggest this is :+1:

2022-12-29 11:12 UTC, franmomu commented on composer.json
>      },
👍 added

2023-01-06 09:35 UTC, IonBazan approved these changes

2023-01-08 14:49 UTC, IonBazan commented
This will currently affect the `AttributeDriver` too: https://github.com/doctrine/mongodb-odm/blob/2.4.x/lib/Doctrine/ODM/MongoDB/Mapping/Driver/AttributeDriver.php as it relies on `Doctrine\Common\Annotations\Reader`. How about we refactor that first to be completely independent from `doctrine/annotations`? We could even drop that package in v3.0.

2023-01-08 15:18 UTC, greg0ire commented
Here is how you could proceed: https://github.com/doctrine/orm/pull/9671

2023-01-09 08:00 UTC, franmomu commented
> This will currently affect the `AttributeDriver` too: https://github.com/doctrine/mongodb-odm/blob/2.4.x/lib/Doctrine/ODM/MongoDB/Mapping/Driver/AttributeDriver.php as it relies on `Doctrine\Common\Annotations\Reader`. How about we refactor that first to be completely independent from `doctrine/annotations`? We could even drop that package in v3.0.

👍 I thought they were independents

2023-01-18 13:23 UTC, alcaeus requested changes, later dismissed
Slapping a "request changes" on this for good measure. As noted before, we first need to make the attribute driver work independently of annotations, then we can make the dependency optional.

That said, I'm very much in favour of removing the hard requirement, and I would also do so in a minor version. We can then think of dropping support for annotations entirely in 3.x.

2024-01-02 13:08 UTC, malarzm approved these changes

2024-01-02 13:08 UTC, malarzm commented on composer.json
> +        "doctrine/annotations": "<1.12 || >=3.0"
FTR conflicting here is IMO OK just because we control the lib and said it's feature complete. Otherwise I'd be against having a conflict section as one could use the lib we're conflicting with, but not use it with ODM.

2024-01-02 13:11 UTC, merged

2024-01-02 13:12 UTC, malarzm commented
I took the liberty and slapped a "BC Break" label for visibility in the release notes.

Thanks @franmomu!

2024-01-02 16:59 UTC, franmomu commented
> I took the liberty and slapped a "BC Break" label for visibility in the release notes.

👍 thanks @malarzm