Support for some new aggregation features
doctrine/mongodb-odm pull request #2499
Opened 2023-01-06 15:50 UTC by aturki

|      Q       |   A
|------------- | -----------
| Type         | feature
| BC Break     | no
| Fixed issues | 2063 (Partially)

#### Summary

Provides implementation of some aggregation operators

2023-01-18 13:15 UTC, alcaeus requested changes
Thank you for adding those operators. I've left some comments, but have not yet reviewed the tests.

I'll also note that methods in the class are currently sorted alphabetically - I'd appreciate it if you could keep the ordering and move newly added methods to the correct place.

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +     */
CI is complaining about this change, it needs to be reverted back:
```suggestion
    /** @throws BadMethodCallException If there is no current switch operator. */
```

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +     * @param int            $place
Both of these annotations are incorrect: they should use `mixed|self` as they accept any valid expression. A string can also be a valid expression, as it can resolve to a field name (i.e. `'$myNumberField'`).

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +     * @param string|null $chars
Same here, these should be `mixed|self`, as they accept any expression that resolves to a string. For example, `['$toString' => 5]` would be a valid value for `$input` as it resolves to a string when executed.

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +    public function ltrim(string $input, ?string $chars = null): self
Parameter types are incorrect.

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +    public function rtrim(string $input, ?string $chars = null): self
Parameter types are incorrect.

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +    public function atan2($expression): self
`atan2` takes two parameters according to the documentation, so the signature for this operator is wrong.

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +    public function convert($expression, $to, ?Expr $onError = null, ?Expr $onNull = null): self
Multiple issues here:
* `$to` can be any valid expression
* `$onError` and `$onNull` can be any valid expression, including a string.

In essence, all parameters here should accept `mixed|self`, and we can include `|null` for `$onError` and `$onNull`.

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +        return $this->operator('$convert', [$expression, $to, $onError, $onNull]);
This would result in the following expression:
```
{
    $convert: [ <expression>, <expression>, <expression>, <expression>]
}
```

This is incorrect, as `$convert` expects an object containing `input` and `to` keys, along with optional `onError` and `onNull` keys as per the documentation.

Instead of passing values as an array, you should pass a hash containing the right keys. I'd suggest omitting `onError` and `onNull` if they are `null` to make sure the default behaviour is not changed. I'd assume passing a `null` value for `onError` would cause the expression to return a `null` value if the conversion is not successful, as opposed to aborting the pipeline with an error.

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> +        return $this->convert($expression, 'bool');
I suggest using `$this->operator('$toBool', $expression)` here and for all other `to...` operators.

2023-01-18 13:15 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Expr.php
> + }
There's an extra space here that phpcs is complaining about:
```suggestion
}
```

2023-02-24 09:23 UTC, alcaeus approved these changes

2023-02-24 09:24 UTC, alcaeus commented
I've extracted an interface from the `Expr` class to ensure that new methods are added to the abstract `Operator` stage. In addition, I've removed the `__call` magic. The idea behind the egg builder is to provide an expressive interface to help people along, and the call magic does the opposite. It was a fallback for when we couldn't have methods named `switch`, `default`, etc.

2023-02-27 10:07 UTC, IonBazan commented on lib/Doctrine/ODM/MongoDB/Aggregation/Operator/GenericOperatorsInterface.php
> +    public function abs($number): self;
Here and all methods below - shouldn't we make it something like:
```suggestion
     * @param static $number
     */
    public function abs($number): static;
```

Since we are targeting PHP 7.4+, we can use `static` typehint. We shouldn't have any reference to `Expr` in this interface.

2023-02-27 13:27 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Aggregation/Operator/GenericOperatorsInterface.php
> +    public function abs($number): self;
I was considering that, but this was added in 8.0, not 7.4: https://php.watch/versions/8.0/static-return-type.

Since the interface is internal, we can make this change once we drop support for 7.4. 👍

2023-02-27 15:12 UTC, IonBazan commented on lib/Doctrine/ODM/MongoDB/Aggregation/Operator/GenericOperatorsInterface.php
> +    public function abs($number): self;
Makes sense, thanks!

2023-02-27 15:12 UTC, IonBazan approved these changes

2023-02-27 15:31 UTC, merged

2023-02-27 15:31 UTC, IonBazan commented
Thanks @aturki! 🚀