Use static data providers
doctrine/mongodb-odm pull request #2512
Opened 2023-03-13 08:09 UTC by IonBazan

#### Summary

Makes all test data providers `static`. This is to fix PHPUnit 10 deprecations.

2023-03-13 09:25 UTC, alcaeus approved these changes
LGTM. Not sure if the Psalm errors are related, they don't really look related.

2023-03-13 23:56 UTC, SenseException requested changes

2023-03-13 23:56 UTC, SenseException commented on phpunit.xml.dist
> +        xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.0/phpunit.xsd"
```suggestion
        xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
```

2023-03-14 23:23 UTC, SenseException approved these changes
I don't see a connection to psalm in this PR, but neither do I see it in the current breaking build on 2.5.x

2023-03-15 06:47 UTC, franmomu approved these changes
Looks like a bug in psalm that after `assertCount`, the type is changed to `Countable` (removing `ArrayAccess`), but apparently the psalm version is the same as in `2.5.x`, so maybe something has changed in phpunit 10

2023-03-16 04:10 UTC, merged