Document new aggregation pipeline builder stages
doctrine/mongodb-odm pull request #2530
Opened 2023-04-24 11:14 UTC by alcaeus

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

This PR documents the new pipeline stages added in 2.6. To make the aggregation builder documentation more browsable, I've extracted the documentation for each stage to a separate documentation page, similar to what is done for mapping annotations.

This refactoring was done in the first commit, with the second commit adding language for new pipeline stages. I recommend reviewing the second commit individually if only reviewing new content.

2023-04-24 22:25 UTC, SenseException requested changes
Thanks for the separation in the mentioned commit.

2023-04-24 22:25 UTC, SenseException commented on docs/en/reference/aggregation-stage-reference.rst
> +Cretaes new documents in a sequence of documents where certain values in a
Please don't write docs in Latin. :-)

```suggestion
Creates new documents in a sequence of documents where certain values in a
```

2023-04-24 22:25 UTC, SenseException commented on docs/en/reference/aggregation-stage-reference.rst
> +- `$unset <https://docs.mongodb.com/manual/reference/operator/aggregation/sortByCount/>`_
```suggestion
- `$unionWith <https://docs.mongodb.com/manual/reference/operator/aggregation/unionWith/>`_
- `$unset <https://docs.mongodb.com/manual/reference/operator/aggregation/unset/>`_
```

2023-04-25 06:43 UTC, jmikola commented on docs/en/reference/aggregation-stage-reference.rst
> +    $builder = $dm->createAggregationBuilder(\Documents\Coffee::class);
Other code blocks have a line break after `<?php`.

```suggestion
    <?php

    $builder = $dm->createAggregationBuilder(\Documents\Coffee::class);
```

2023-04-25 06:43 UTC, jmikola commented on docs/en/reference/aggregation-stage-reference.rst
> +                    $builder->expr()->multiply('$value', 5),
Seeing `$value` here alongside a `value()` builder method is a bit confusing.

I assume `$value` here is referencing a field path within the document. Would it help to use `$fieldPath` in the example to make this more self-documenting?

2023-04-25 06:43 UTC, jmikola commented on docs/en/reference/aggregation-stage-reference.rst
> +``$lastAggregateRun`` variable) and updates the ``monthlyOrderStats`` collection
`$lastAggregateRunAt` or `$lastAggregatedAt` would be more clear for a date field. On my first read, I didn't realize this was a date.

Might also help to say it's a `UTCDateTime` type. I didn't check the Orders model but I assume that's what you're using here.

2023-04-25 06:43 UTC, jmikola commented on docs/en/reference/aggregation-stage-reference.rst
> +                ->output()
Did you mean to call `output()` twice here?

The [`$setWindowFields` syntax](https://www.mongodb.com/docs/manual/reference/operator/aggregation/setWindowFields/#syntax) suggests that properties under `output` are field names, so I'd expect the builder to call `output()->field()`.

2023-04-25 06:43 UTC, jmikola commented on docs/en/reference/aggregation-stage-reference.rst
> +        ->unset('customer', 'shippingAddress.street', 'billingAddress.street')
I find it interesting that `unset()` takes multiple arguments while `excludeFields()` and `includeFields()` take a list of fields as a single array argument.

Is there a particular reason you avoided variadics for exclude/include, or are they just older? Is this something worth addressing in a subsequent PR? Are there other functions with a similar inconsistency?

2023-04-25 07:03 UTC, alcaeus commented on docs/en/reference/aggregation-stage-reference.rst
> +                    $builder->expr()->multiply('$value', 5),
Changed to `$someField` to indicate that it could be any field. At this point in the docs I'd assume people are familiar with the syntax, but it still doesn't hurt to make it a little clearer.

2023-04-25 07:04 UTC, alcaeus commented on docs/en/reference/aggregation-stage-reference.rst
> +``$lastAggregateRun`` variable) and updates the ``monthlyOrderStats`` collection
Renamed to `$lastAggregateRunAt`. The type here doesn't matter as much as the aggregation builder is aware of the mapping and thus able to convert types as necessary. It's thus possible to use either a `DateTimeInterface` or `UTCDateTime` instance.

2023-04-25 07:05 UTC, alcaeus commented on docs/en/reference/aggregation-stage-reference.rst
> +                ->output()
Great catch, the second call to `output()` is indeed unnecessary.

2023-04-25 07:11 UTC, alcaeus commented on docs/en/reference/aggregation-stage-reference.rst
> +        ->unset('customer', 'shippingAddress.street', 'billingAddress.street')
I'm not entirely sure if there was any other reason, but back when the `$project` stage builder was added there was no way to use variadic args other than mentioning in the docs and then using `func_get_args`. However, we did that in a few other places, so this may very well have been missed by me.

Since we now have a good way to handle variadic args, I figured it would make more sense to build it this way. In my head I've even gone a step further and considered using named variadic args. Consider the following:
```php
// Builder signature: public function set(mixed ...$fields): static;

// Usage
$builder->set(
    numOrders: $builder->expr()->countDocuments(),
    totalValue: $builder->expr()->sum('$orderTotal')
);
```

The only downside with this would be setting more complex field names (e.g. nested documents or other field names containing characters that aren't allowed as PHP identifiers). There is a fallback way to allow a single array argument instead of the variadic list (think `array_keys($fields) === [0] && is_array($fields[0])`), but I'm not too sure about it yet. This might be part of the builder that we're designing for PHPLIB and Laravel, which would eventually also make its way into ODM.

2023-04-26 09:58 UTC, jmikola commented on docs/en/reference/aggregation-stage-reference.rst
> +                ->output()
I see you re-requested a review, but I don't think you pushed any changes from my last review.

2023-04-26 11:04 UTC, alcaeus commented on docs/en/reference/aggregation-stage-reference.rst
> +                ->output()
Oh, dang, I missed that. I've pushed changes now.

2023-04-26 12:07 UTC, jmikola approved these changes
Unrelated to this PR, but the CS and PHPStan errors suggest you may want to limit the language version used to the oldest supported.

2023-04-26 13:14 UTC, alcaeus commented
> Unrelated to this PR, but the CS and PHPStan errors suggest you may want to limit the language version used to the oldest supported.

Yep, I'll have to check out the various failures separately.

2023-04-26 21:13 UTC, SenseException approved these changes

2023-04-27 06:14 UTC, merged