Support search indexes in mappings and SchemaManager
doctrine/mongodb-odm pull request #2630
Opened 2024-04-24 17:57 UTC by jmikola

|      Q       |   A
|------------- | -----------
| Type         | feature
| BC Break     | no
| Fixed issues | [PHPORM-38](https://jira.mongodb.org/browse/PHPORM-38)

#### Summary

2024-04-29 07:16 UTC, alcaeus reviewed
Initial review looks good. There's a number of PHPStan issues due to not properly specifying all array key/value pairs. I'll let you decide whether it's worth specifying them all or whether you'd rather add the errors to the baseline.

2024-04-29 07:16 UTC, alcaeus commented on doctrine-mongo-mapping.xsd
> +    <xs:choice minOccurs="0" maxOccurs="unbounded">
Is there a reason to have an empty `search-indexes` element anywhere? Otherwise you could consider using `minOccurs="1"`.

2024-04-29 07:16 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/SchemaManager.php
> +    public function createSearchIndexes(): void
Leaving a note to follow up on later, but these methods aren't invoked by the schema commands yet. Since search indexes are an Atlas-only feature, I would suggest duplicating the existing logic for managing indexes instead of combining them with regular indexes.

2024-04-29 13:35 UTC, jmikola commented on lib/Doctrine/ODM/MongoDB/SchemaManager.php
> +    public function createSearchIndexes(): void
I'm still working through this in the command classes and forgot to preemptively leave a comment about this last week. I was on the fence about creating entirely new methods since that would change the public interface for AbstractCommand. If you're not concerned about that being a BC break, I have no qualms in doing so.

Otherwise, I planned to incorporate this into the `--index` option and introduce a supporting option to enable/disable search indexes. That feels clunkier though, so I'm certainly in favor of a new, explicit option.

2024-04-29 13:58 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/SchemaManager.php
> +    public function createSearchIndexes(): void
While `AbstractCommand` is not marked as internal, I'm not particularly concerned about people extending it, and we can work around it by providing a default implementation for the new methods instead of leaving them empty to avoid compile errors. Any objections to that plan @malarzm?

2024-04-29 14:05 UTC, jmikola commented on lib/Doctrine/ODM/MongoDB/SchemaManager.php
> +    public function createSearchIndexes(): void
A default implementation seems prudent, even if it'd only be useful internally for ShardCommand (where I'm presently throwing a BadMethodCallException like other unsupported methods).

2024-04-29 15:07 UTC, malarzm commented on lib/Doctrine/ODM/MongoDB/SchemaManager.php
> +    public function createSearchIndexes(): void
I'd say do whatever you guys need with `AbstractCommand`. I deem it highly unlikely that somebody extended those. And if they did they'll be smart enough to fix it themselves ;)

2024-04-29 17:22 UTC, jmikola commented on doctrine-mongo-mapping.xsd
> +    <xs:choice minOccurs="0" maxOccurs="unbounded">
This was copied from the `<indexes>` definition, but I see no reason we can't use `minOccurs="1"` here. I'll leave `<indexes>` as-is, though.

2024-05-01 20:16 UTC, jmikola commented
Sharding failures seem unrelated: https://github.com/doctrine/mongodb-odm/actions/runs/8914210744/job/24481504241?pr=2630

2024-05-02 08:36 UTC, GromNaN commented on lib/Doctrine/ODM/MongoDB/Mapping/Annotations/SearchIndex.php
> +        public ?bool $dynamic = null,
Wouldn't it be better to set actual default values rather than nullable types? That would document the default values in the code directly.

```suggestion
        public bool $dynamic = false,
```

But then, my suggestion isn't consistent with the rest of the Doctrine attributes.

2024-05-02 08:36 UTC, GromNaN commented on tests/Documents/CmsArticle.php
> +#[ODM\SearchIndex(dynamic: true)]
Could you use all the fields in the attribute to make the test more exhaustive?

2024-05-02 11:06 UTC, alcaeus requested changes

2024-05-02 11:06 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/AbstractCommand.php
> +    }
👍 for adding default implementations for all methods in this class.

2024-05-02 11:06 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
> +                default => throw new UnhandledMatchError($option),
This is standard behaviour in PHP, see https://3v4l.org/LU66Z.
```suggestion
```

2024-05-02 11:06 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/DropCommand.php
> +                default => throw new UnhandledMatchError($option),
```suggestion
```

2024-05-02 11:06 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
> +            ->addOption('disable-search-indexes', null, InputOption::VALUE_NONE, 'Do not update search indexes')
I'm aware the naming is consistent with `disable-validators`, but wouldn't `skip-search-indexes` be more appropriate?

2024-05-02 18:25 UTC, jmikola commented on lib/Doctrine/ODM/MongoDB/Mapping/Annotations/SearchIndex.php
> +        public ?bool $dynamic = null,
I did originally consider this, but thought it best to minimize what ends up in the definition shipped to `createSearchIndexes`.

2024-05-02 18:27 UTC, jmikola commented on tests/Documents/CmsArticle.php
> +#[ODM\SearchIndex(dynamic: true)]
The mapping tests are exhaustive in their use of all options. This model is only used for the SchemeManager tests, in which we assert that _something_ is passed along to the mocked MongoDB\Collection methods. That is based on prior art for the standard index tests.

2024-05-02 18:29 UTC, jmikola commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
> +                default => throw new UnhandledMatchError($option),
Indeed it is; however, PHPStan doesn't approve: https://github.com/phpstan/phpstan/issues/4451

I can replace this with a baseline addition. I'm currently only relying on the baseline for the truly unreasonable issues (`fields` and `analyzers` options).

2024-05-02 18:30 UTC, jmikola commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
> +            ->addOption('disable-search-indexes', null, InputOption::VALUE_NONE, 'Do not update search indexes')
SGTM. I'll make the change.

2024-05-03 08:16 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
> +                default => throw new UnhandledMatchError($option),
I'll leave this up to you and chalk this up as another point against PHPStan. Feel free to resolve after reading.

2024-05-03 08:19 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
> +            ->addOption('disable-search-indexes', null, InputOption::VALUE_NONE, 'Do not update search indexes')
I'd say for now we can leave create and drop as-is, but I agree that it's unfortunate to have to redefine the entire list when wanting to exclude a single item, especially as that can create issues when we add new functionality. A dedicated `skip-<feature>` or `include-<feature>` (for optional things) might be better, despite it meaning more command-line arguments. Let's create a ticket for this and put it on the map for a future refactoring of those commands.

2024-05-06 15:44 UTC, jmikola commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
> +            ->addOption('disable-search-indexes', null, InputOption::VALUE_NONE, 'Do not update search indexes')
Opened https://github.com/doctrine/mongodb-odm/issues/2634. I only proposed `skip-<feature>` as the commands already support opt-in behavior. For example, CreateCommand's `--collection` option would accomplish the same thing as `include-collection`, assuming both would disable the `$createOrder` and expect everything to be explicitly requested (as `--collection` does today).

2024-05-06 15:44 UTC, jmikola commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/CreateCommand.php
> +                default => throw new UnhandledMatchError($option),
In the interest of keeping the code cleaner, I'll remove the useless `default` cases and track this in the PHPStan baseline.

2024-05-06 16:51 UTC, jmikola commented
Psalm is failing due to [two unused baseline entries](https://github.com/doctrine/mongodb-odm/actions/runs/8972457667/job/24640499243?pr=2630#step:6:27), but I'm unable to reproduce that locally with PHP 8.2 (same as is used in CI):

```
Error: lib/Doctrine/ODM/MongoDB/UnitOfWork.php:0:0: UnusedBaselineEntry: Baseline for issue "TypeDoesNotContainType" has 1 extra entry. (see https://psalm.dev/316)
Error: tests/Doctrine/ODM/MongoDB/Tests/SchemaManagerTest.php:0:0: UnusedBaselineEntry: Baseline for issue "TypeDoesNotContainType" has 1 extra entry. (see https://psalm.dev/316)
```

UnitOfWork is also entirely unrelated to this PR, so I'm not sure what to make of that.

2024-05-06 16:52 UTC, jmikola commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
> +            ->addOption('disable-search-indexes', null, InputOption::VALUE_NONE, 'Do not update search indexes')
Renamed this to `skip-search-indexes` and added the same option to CreateCommand and DropCommand. #2634 can be used for renaming `disable-validators` and adding additional `skip-<feature>` options if desired.

2024-05-07 06:51 UTC, alcaeus commented
> Psalm is failing due to [two unused baseline entries](https://github.com/doctrine/mongodb-odm/actions/runs/8972457667/job/24640499243?pr=2630#step:6:27), but I'm unable to reproduce that locally with PHP 8.2 (same as is used in CI):

This could be related to using an outdated psalm version - I was able to reproduce it locally with psalm 5.24.0.

2024-05-07 06:51 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php
> +            ->addOption('disable-search-indexes', null, InputOption::VALUE_NONE, 'Do not update search indexes')
Sounds good, thank you!

2024-05-07 06:52 UTC, alcaeus approved these changes
LGTM with psalm issues fixed.

2024-05-07 06:53 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/Mapping/Annotations/SearchIndex.php
> +        public ?bool $dynamic = null,
Agree - we've typically used nullable bools when we want to omit values from the command unless they were explicitly specified, and the only way to achieve this is by using a `null` default value.

2024-05-08 13:39 UTC, jmikola commented
Docs are still in progress (very not fun).

2024-05-10 20:24 UTC, jmikola commented on tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTestCase.php
> + *     "embedded_phone_number"={"type"="embeddedDocuments", "dynamic"=true},
Note: [embeddedDocuments](https://www.mongodb.com/docs/atlas/atlas-search/field-types/embedded-documents-type/) is used because the field is mapped as EmbedMany:

```
@ODM\EmbedMany(targetDocument=Phonenumber::class, name="embedded_phone_number")
```

If the relationship was EmbedOne then [document](https://www.mongodb.com/docs/atlas/atlas-search/field-types/document-type/) would be appropriate.

2024-05-13 16:25 UTC, jmikola commented on tests/Doctrine/ODM/MongoDB/Tests/Mapping/AbstractMappingDriverTestCase.php
> + *     "embedded_phone_number"={"type"="embeddedDocuments", "dynamic"=true},
I've ensured one of the docs examples uses `embeddedDocuments`.

2024-05-22 07:33 UTC, alcaeus approved these changes
Gave the docs a read and they look good to me. Since we can't easily test docs generation, I'd suggest we merge this as is and fix any RST issues after the fact.

2024-05-22 12:53 UTC, merged

2025-07-07 12:49 UTC, stof commented on docs/en/reference/search-indexes.rst
> +         * @SearchIndex(
shouldn't this show an eample using attributes rather than annotations ?

2025-07-16 17:16 UTC, jmikola commented on docs/en/reference/search-indexes.rst
> +         * @SearchIndex(
It looks like that was addressed in https://github.com/doctrine/mongodb-odm/commit/37013acdf1db8c10e2982e0700f72682d1fd2339