doc: Update custom mapping example
doctrine/mongodb-odm pull request #2654
Opened 2024-06-25 13:12 UTC by GromNaN

|      Q       |   A
|------------- | -----------
| Type         | doc
| BC Break     | no
| Fixed issues | -

#### Summary

The previous example was a simplified copy of the `date` type. In order to present something more useful, the new example is inspired by the [codecs tutorial](https://www.mongodb.com/docs/php-library/current/tutorial/codecs/).

Also initializing tests on documentation examples.

2024-06-25 22:16 UTC, SenseException requested changes

2024-06-25 22:16 UTC, SenseException commented on docs/en/reference/custom-mapping-types.rst
> +        public function convertToDatabaseValue($value): ?array
```suggestion
        public function convertToDatabaseValue($value): array
```

2024-06-25 22:16 UTC, SenseException commented on docs/en/reference/custom-mapping-types.rst
> +        public function convertToPHPValue($value): ?DateTimeImmutable
```suggestion
        public function convertToPHPValue($value): DateTimeImmutable
```

2024-06-25 22:16 UTC, SenseException commented on tests/Documentation/CustomMapping/DateTimeWithTimezoneType.php
> +    public function convertToDatabaseValue($value): ?array
Do the methods have to be nullable for a reason?

2024-06-26 05:34 UTC, GromNaN commented on tests/Documentation/CustomMapping/DateTimeWithTimezoneType.php
> +    public function convertToDatabaseValue($value): ?array
Thank you for spotting this error. Indeed, no need to manage `null` values.

2024-06-26 09:09 UTC, alcaeus approved these changes
LGTM with a minor suggestion for checks

2024-06-26 09:09 UTC, alcaeus commented on docs/en/reference/custom-mapping-types.rst
> +            $timeZone = new DateTimeZone($value['tz']);
Just a suggestion, but this could benefit from some value checks:
```php
if (! is_array($value) || ! isset($value['utc'], $value['tz'])) {
    throw new Exception(); // TODO: throw correct exception class
}
```

The end result will be the same, but I feel like there can be more useful information in the exception message rather than letting PHP throw its type errors. Not sure if there's prior art for this in our type, so feel free to disregard and leave this as an exercise to the user.

2024-06-26 09:43 UTC, GromNaN commented on docs/en/reference/custom-mapping-types.rst
> +            $timeZone = new DateTimeZone($value['tz']);
Absolutely, it's easy to be sure of a property's value, especially with typing, but there can always be surprises with database content, especially when there's no schema (which is certainly very common).

2024-06-26 21:50 UTC, SenseException commented
@GromNaN Please update your [commit messages](https://www.doctrine-project.org/contribute/index.html#crafting-meaningful-commit-messages) to more meaningful ones. Don't repeat messages and don't use just one word.

2024-06-26 21:57 UTC, GromNaN commented
> @GromNaN Please update your [commit messages](https://www.doctrine-project.org/contribute/index.html#crafting-meaningful-commit-messages) to more meaningful ones. Don't repeat messages and don't use just one word.

The commit history is not very meaningful. I squash and update the unique commit message before merging. This commits are juste a raw historic of my changes and fixes that help when reviewing a second time the PR.

2024-06-27 09:30 UTC, GromNaN commented
@SenseException I squashed the commits in this PR.

2024-06-28 23:13 UTC, SenseException approved these changes

2024-06-28 23:13 UTC, merged