Update UnitOfWork.php
doctrine/mongodb-odm pull request #2676
Opened 2024-09-17 19:40 UTC by magnetik

|      Q       |   A
|------------- | -----------
| Type         | bug/feature/improvement
| BC Break     | yes/no
| Fixed issues | 

#### Summary

2024-09-18 18:37 UTC, magnetik commented
(I do not have a local setup with mongo, so I'm sort of using the actions to test.. sorry about that)

2024-09-19 06:05 UTC, alcaeus requested changes

2024-09-19 06:05 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/UnitOfWork.php
> +                    // }
Please remove commented code
```suggestion
```

2024-09-19 06:11 UTC, alcaeus approved these changes
LGTM with the PHPCS fix and suppression.

2024-09-19 06:11 UTC, alcaeus commented on lib/Doctrine/ODM/MongoDB/UnitOfWork.php
> +                    if ($dbOrgValue == $dbActualValue) {
Note that you can suppress the phpcs warning in this file, as it's appropriate to use `==` here. `===` would bypass the object comparison handler implemented for `UTCDateTime` and would thus break the behaviour again.

2024-09-19 07:19 UTC, magnetik commented on lib/Doctrine/ODM/MongoDB/UnitOfWork.php
> +                    if ($dbOrgValue == $dbActualValue) {
done (I think)

2024-09-19 11:02 UTC, magnetik commented on lib/Doctrine/ODM/MongoDB/UnitOfWork.php
> +                    if ($dbOrgValue == $dbActualValue) {
How can I find the right rule to silence this ?
Is it SlevomatCodingStandard.Operators.DisallowEqualOperators maybe ?

2024-09-19 15:47 UTC, magnetik commented
if you know how to fix the style issue, feel free to fix it directly there if you want to save some time to restart the checks later ^^

Thanks !

2024-09-19 19:52 UTC, malarzm commented
It goes like this: https://github.com/doctrine/mongodb-odm/blob/8e0deb186540a89111181c3be89924a3d791045c/lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/ValidateCommand.php#L44-L45

2024-09-20 12:31 UTC, merged

2024-09-20 12:31 UTC, alcaeus commented
Thanks @magnetik!